language: ruby
rvm:
- 2.1.2
deploy:
  provider: heroku
  api_key:
    secure: T/rkhibwg2EBQhDVff/E04HWIJVivfR6vNq7aGQUq2cMizDQgi4657ykyQxljHmyrdRFdY7DuPc76qj4Zo+wTxH9OiZPrDHaxacxn8Kd6xPH4asZDsL9oiFf8dEVWS2XOIPwDHLykHr4LIcxoiepqlpGPQ1UREi/DynUJ6umgaY=
  app: mighty-river-7140
  on:
    repo: ryuichiueda/rakuten_enpit_example
